# Generated by Django 3.2.6 on 2021-08-17 12:33

import apps.models.alliance.models
from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='카테고리 이름')),
                ('is_active', models.BooleanField(default=True, verbose_name='카테고리 활성')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='메뉴 카테고리')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='음식점 이름')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=10, verbose_name='위도')),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=10, verbose_name='경도')),
                ('min_price', models.CharField(max_length=10, verbose_name='최소주문금액')),
                ('payment_method', models.CharField(max_length=30, verbose_name='결제방법')),
                ('delivery_time', models.CharField(max_length=20, verbose_name='배달 시간')),
                ('delivery_tip', models.CharField(max_length=10, verbose_name='배달 팁')),
                ('information', models.TextField(blank=True, null=True, verbose_name='정보')),
                ('country_origin', models.TextField(blank=True, null=True, verbose_name='원산지')),
                ('announcement', models.TextField(blank=True, null=True, verbose_name='공지사항')),
                ('announcement_photo', models.ImageField(blank=True, null=True, upload_to=apps.models.alliance.models.get_announcement_photo_path, verbose_name='공지사항 이미지')),
                ('paid_service', models.IntegerField(choices=[(0, '울트라콜'), (1, '기본'), (2, '오픈서비스')], default=1, verbose_name='유료서비스')),
                ('is_active', models.BooleanField(default=True, verbose_name='가게 활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alliance.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=30, verbose_name='상호명')),
                ('business_hours', models.CharField(max_length=30, verbose_name='영업 시간')),
                ('closed_day', models.CharField(max_length=30, verbose_name='휴무일')),
                ('phone_number', models.CharField(max_length=20, verbose_name='전화번호')),
                ('areas_interest', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10, verbose_name='관심지역(4곳)'), blank=True, size=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alliance.restaurant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_photo', models.ImageField(blank=True, upload_to=apps.models.alliance.models.get_review_photo_path, verbose_name='음식 사진')),
                ('score', models.IntegerField(help_text='1~5점 사이로 입력해주세요.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='평점')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_restaurants', to='alliance.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MenuInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='메뉴 이름')),
                ('photo', models.ImageField(blank=True, upload_to=apps.models.alliance.models.get_food_menu_photo_path, verbose_name='메뉴이미지')),
                ('information', models.TextField(verbose_name='메뉴 소개')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alliance.menucategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='menucategory',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alliance.restaurant'),
        ),
        migrations.CreateModel(
            name='EntrepreneurInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representative_name', models.CharField(max_length=10, verbose_name='대표자 이름')),
                ('business_license_photo', models.ImageField(upload_to=apps.models.alliance.models.get_business_license_photo_path, verbose_name='사업자등록증(사본)')),
                ('business_name', models.CharField(max_length=30, verbose_name='상호명')),
                ('business_address', models.CharField(max_length=50, verbose_name='사업자 주소')),
                ('business_license_number', models.CharField(max_length=50, verbose_name='사업자 등록 번호')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alliance.restaurant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
