# Generated by Django 3.2.6 on 2021-08-17 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alliance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='쿠폰 이름')),
                ('discount_amount', models.IntegerField(default=0, verbose_name='할인 금액')),
                ('valid_period_start', models.DateField(blank=True, null=True, verbose_name='유효기간 시작일')),
                ('valid_period_end', models.DateField(blank=True, null=True, verbose_name='유효기간 종료일')),
                ('is_used', models.BooleanField(default=False, verbose_name='쿠폰 사용 확인')),
                ('is_expired', models.BooleanField(default=False, verbose_name='쿠폰 만료')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_amount', models.IntegerField(default=0, verbose_name='적립 포인트')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PointHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, '사용'), (1, '취소')], default=0, verbose_name='사용처리')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.point')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alliance.restaurant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_price', models.IntegerField(default=0, verbose_name='결제액')),
                ('payment_status', models.IntegerField(choices=[(0, '결제 요청'), (1, '결제 취소'), (2, '결제 실패'), (3, '결제 완료'), (4, '전체 환불')], default=0, verbose_name='결제상태')),
                ('method_status', models.IntegerField(choices=[(0, '즉시 결제'), (1, '만나서 결제'), (2, '현금 결제')], default=0, verbose_name='결제수단')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_payment', to='transaction.coupon')),
                ('point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='point_payment', to='transaction.point')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_payment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, '사용'), (1, '취소')], default=0, verbose_name='사용처리')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_history', to='transaction.coupon')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rest_history', to='alliance.restaurant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
