# Generated by Django 3.2.6 on 2021-08-17 12:33

import apps.models.account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='이메일')),
                ('nickname', models.CharField(max_length=50, verbose_name='닉네임')),
                ('phone', models.CharField(max_length=20, verbose_name='휴대폰')),
                ('birthday', models.DateField(verbose_name='생년월일')),
                ('rating', models.IntegerField(choices=[(0, '일반'), (1, '실버'), (2, '골드'), (3, 'VIP')], default=0, verbose_name='등급')),
                ('photo', models.ImageField(blank=True, upload_to=apps.models.account.models.get_user_photo_path, verbose_name='프로필사진')),
                ('is_active', models.BooleanField(default=False, verbose_name='계정활성')),
                ('is_owner', models.BooleanField(default=False, verbose_name='사장님')),
                ('is_admin', models.BooleanField(default=False, verbose_name='관리자')),
                ('is_withdrawal', models.BooleanField(default=False, verbose_name='탈퇴')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserDeliveryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
