# Generated by Django 3.2.6 on 2021-08-17 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('alliance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdeliverylist',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alliance.restaurant'),
        ),
        migrations.AddField(
            model_name='shoppingbasket',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alliance.restaurant'),
        ),
    ]
