# Generated by Django 3.2.6 on 2021-08-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approval',
            field=models.BooleanField(default=False, verbose_name='가입승인'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='계정활성'),
        ),
    ]
